### ISSUE TITLE
Getting an error on FETCH against faktory 0.6.1

### ISSUE THREAD

**Issue by valo** [cjbottaro/faktory_worker_ex#1]
I am getting the following error when running the worker against faktory 0.6.1:

```
[error] GenServer #PID<0.374.0> terminating
** (stop) exited in: :gen_server.call(#PID<0.370.0>, {:recv, -1})
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in :prim_inet.recv0/3
            :prim_inet.recv0(#Port<0.9227>, -1, 4000)
            (faktory_worker_ex) lib/faktory/connection.ex:94: Faktory.Connection.handle_call/3
            (connection) lib/connection.ex:488: Connection.handle_call/3
            (stdlib) gen_server.erl:636: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:665: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
    (stdlib) gen_server.erl:206: :gen_server.call/2
    (faktory_worker_ex) lib/faktory/protocol.ex:129: Faktory.Protocol.rx/2
    (faktory_worker_ex) lib/faktory/protocol.ex:28: Faktory.Protocol.fetch/2
    (poolboy) /Users/valentin/workspace/santiment/sanbase2/deps/poolboy/src/poolboy.erl:76: :poolboy.transaction/3
    (faktory_worker_ex) lib/faktory/worker.ex:116: Faktory.Worker.with_conn/2
    (faktory_worker_ex) lib/faktory/worker.ex:58: Faktory.Worker.fetch/1
    (faktory_worker_ex) lib/faktory/worker.ex:31: Faktory.Worker.handle_cast/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", :next}
State: %{__struct__: Faktory.Configuration.Worker, concurrency: 20, error: nil, fn: nil, host: "localhost", job: nil, middleware: [], name: :"worker/default", pool: 20, port: 7419, queues: ["greeter"], start_time: nil, wid: "0a435ca5815c78bf", worker_pid: nil}
```

I tried to debug the problem and it seems that the parsed size on this line is `-1`: https://github.com/cjbottaro/faktory_worker_ex/blob/master/lib/faktory/protocol.ex#L111

I am not sure what this `$` in the response means. Any pointers to the faktory documentation about that? Any help will be appreciated.

**Comment by valo** [comment]
I found it! Seems like this is a Null Bulk String which is encoded with `$-1\r\n`. I can try to tweak the code to support this. Here is the spec: https://redis.io/topics/protocol
